version: '3'

networks:
    default:
      external:
        name: local-net
    proxy:
      driver: bridge
      driver_opts:
          com.docker.network.enable_ipv6: "true"
      ipam:
          driver: default
          config:
            - subnet: 172.16.238.0/24

services:

  db:
    image: mysql
    env_file: 
      - ./.env
    ports:
    - "3306:3306"
    expose:
      - '3306'
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=test
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - my-datavolume:/var/lib/mysql
    networks:
        default:
          ipv4_address: 10.128.0.8
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf
    ports:
      - "80:27015"
      - "443:443"
    environment:
      - NGINX_HOST=short.me
      - NGINX_PORT=80
    networks:
      proxy:
        ipv4_address: 172.16.238.20
      default:
  link_shorterner:
    build:
        context: ./backend_server
        dockerfile: Dockerfile
    image: link_shorterner:latest
    env_file: 
        - ./.env
    command:     bash -c "sleep 10 && python3 server.py"
    restart: always
    networks:
        default:
            ipv4_address: 10.128.0.10

    ports:
        - 27015:27015


volumes:
  my-datavolume:

